#!/bin/sh
set -euf

##
# Demo Trello API to get a board's cards
#
# Syntax:
#
#     get-board-to-card-id-list <board_id>
#
# Example:
#
#     get-board-to-card-id-list 979530daf10c65144e70e49871c05ac5
#
# This script needs environmental variables:
#
#   * KEY is your Trello API key a.k.a. public application developer key
#
#   * TOKEN is your authorization token a.k.a. private personal access token
##

board_id="$1"

curl -sSL "https://api.trello.com/1/boards/$board_id/cards?key=$KEY&token=$TOKEN" | 
jq -r ".[].id"
