#!/bin/sh
set -euf

##
# Demo Trello API to get a board's cards' custom fields
#
# Syntax:
#
#     get-board-to-card-custom-fields <board_id>
#
# Example:
#
#     get-board-to-card-custom-fields 979530daf10c65144e70e49871c05ac5
#
# This script needs environmental variables:
#
#   * KEY is your Trello API key a.k.a. public application developer key
#
#   * TOKEN is your authorization token a.k.a. private personal access token
##

board_id="$1"

curl -sSL "https://api.trello.com/1/boards/$board_id/?key=$KEY&token=$TOKEN&fields=name&cards=visible&card_fields=name&customFields=true&card_customFieldItems=true" |
jq .
