#!/bin/sh

##
# Demo Trello API to get boards' cards' custom fields
#
# Syntax:
#
#     trello-api-get-board-id-list-to-card-custom-fields <board id> …
#
# Example:
#
#     trello-api-get-board-id-list-to-card-custom-fields 979530daf10c65144e70e49871c05ac5
#
# This script needs environmental variables:
#
#   * KEY is your Trello API key a.k.a. public application developer key
#
#   * TOKEN is your authorization token a.k.a. private personal access token
##

base="https://api.trello.com/1"

for board_id in "$@"; do
    curl -sSL "$base/boards/$board_id/?key=$KEY&token=$TOKEN&fields=name&cards=visible&card_fields=name&customFields=true&card_customFieldItems=true"
done
